# Configuration file
#

tabwidth = 4      # Display width of a tab character
autoTab = true    # Insert indentation string in lieu of tab character
tabDetect = true  # Detect indentation character
tabString = "\t"  # Default indentaion string

[filetypes.toml]
ext = ["toml"]
parent = "sh"

  [[ syntax_rules ]]
  pattern = "//.*$"
  fgcolor = "cyan"


